spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/car_parts_shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
#  servlet:
#    multipart:
#      max-file-size: 1MB
#      max-request-size: 5MB
  mvc:
    hidden-method:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

